start:
  - run: ./.backend/start.sh
  - on: windows
    run: .\.backend\start.cmd
stop:
  - run: ./.backend/stop.sh
  - on: windows
    run: .\.backend\stop.cmd


auto_start: false

env:
  - DEBUG=false

stdout_log: debug
stderr_log: warn
