start:
  - on: windows
    run: ./.backend/start.cmd
  - run: ./.backend/start.sh
stop:
  - on: windows
    run: ./.backend/stop.cmd
  - run: ./.backend/stop.sh


auto_start: false

env:
  - DEBUG=false

stdout_log: debug
stderr_log: warn

http_proxy:
  prefix: /api/
  address: unix://../storage/.sock
