start:
  - on: windows
    run: |
      ./.backend/start.cmd
  - run: |
      ./.backend/start.sh
stop:
  - on: windows
    run: |
      ./.backend/stop.cmd
  - run: |
      ./.backend/stop.sh


auto_start: false

env:
  - INTERVAL=10s
  - TABLE_NAME=example

stdout_log: debug
stderr_log: warn
